name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: docs/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: docs

      - name: Build website
        run: yarn build
        working-directory: docs

      - name: List build output
        run: ls -R docs/build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build
          publish_branch: gh-pages
          enable_jekyll: false
          cname: info.grinduino.com
          force_orphan: true
          
      - name: Check gh-pages branch
        if: success()
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          ls -la
          cat CNAME
